# Run the command
# heroku run db:migrate
# after pushing to heroku via the
# git push heroku master
# command
# heroku automatically creates the database, but it still needs to be manually migrated
# p.s. heroku run is the command that allows you to run console commands on the heroku app

default: &default
    adapter: postgresql
    encoding: unicode
    pool: 5

development:
    adapter: postgresql
    encoding: unicode
    database: chirpy_dev
    pool: 5
    host: localhost
    port: 5432

test:
    adapter: postgresql
    encoding: unicode
    database: chirpy_test
    pool: 5
    host: localhost
    port: 5432

