default: &default
    adapter: postgresql
    encoding: unicode
    pool: 5

development:
    adapter: postgresql
    encoding: unicode
    database: chirpy_dev
    pool: 5
    host: localhost
    port: 5432

test:
    adapter: postgresql
    encoding: unicode
    database: chirpy_test
    pool: 5
    host: localhost
    port: 5432

